### PR TITLE
Fixes for Django 4.x

### PR DESCRIPTION
**Pull request by capriele**

### CODE REVIEW

**Comment by stefanoostwegel** [comment]
+1 !!!!

I added the fix manually to make it run, hope for it to be pushed someday.

**Comment by stefanoostwegel** [comment]
Im not really good with creating pull requests, but there was another fixed required in the process_tasks.py
14: from django.db import close_old_connections

**Comment by iamjonmiller** [comment]
@capriele @stefanoostwegel  I am maintaining an updated version of this package until this is officially updated. Was going to publish my fixes, but saw you had this open so I gave you credit too, https://pypi.org/project/django-background-tasks-updated/

**Review by naanur — APPROVED** [review]

**Comment by mohitpandeyji** [comment]
when will this be merged , as lots of  projects using this

**Comment by iamjonmiller** [comment]
> This doesn't hold up for Python 3.12 as `imp` was removed

@CDWimmer Published an update yesterday with full 3.12 compatibility

**Comment by CDWimmer** [comment]
> > This doesn't hold up for Python 3.12 as `imp` was removed
> 
> @CDWimmer Published an update yesterday with full 3.12 compatibility

Legend

**Comment by aviya-bm** [comment]
Can this land? The 3.12 fix is a big improvement alone.

**Comment by CDWimmer** [comment]
> Can this land? The 3.12 fix is a big improvement alone.

@aviya-bm https://pypi.org/project/django-background-tasks-updated/
John Miller maintains a fork, recommend switching to use that instead of this.

**Comment by iamjonmiller** [comment]
Resolved in #300

**Pull request closed without merging**
